version = 0.1
[default.deploy.parameters]
stack_name = "LambdaEC2DailySnapshot-SamApp"
resolve_s3 = true
s3_prefix = "LambdaEC2DailySnapshot-SamApp"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
